### PR TITLE
Supress log statistics INFO log --> DEBUG

### PR DESCRIPTION
**Pull request by reinzor**

### CODE REVIEW

**Comment by novatel-applications-engineering** [comment]
Hi @reinzor 

Thank you for the pull request. 

We are discussing this change internally.

Could you please clarify the reason behind this change? Are you running into issues with this being output too frequently?

**Comment by reinzor** [comment]
> Could you please clarify the reason behind this change? Are you running into issues with this being output too frequently?

Yes, we are working on cleaning up the output logs of our system. These messages are being logged frequently and pollute the output log.

**Comment by Timple** [comment]
This kind of debug information would typically be well suited on a `/diagnostics` topic: https://github.com/novatel/novatel_oem7_driver/issues/3

Should work better than repetitive prints

**Comment by novatel-applications-engineering** [comment]
Thanks for the clarification. We are looking further into this. I will let you know when I have an update.

**Comment by novatel-applications-engineering** [comment]
Hi @reinzor,

We discussed internally and appreciate you suggestion to reduce console output. We have decided on a solution that condenses the console output from outputLogStatistics from 20 lines using a default driver configuration to 1 line each time it is called. We did not want to fully move it off of the INFO stream as it is useful for users to rapidly verify receiver connection and if specific logs are being collected from the receiver.

I'm not able to commit to this pull request due to it coming from your library. Our changes to the function outputLogStatistics that we will push are:
```
    void outputLogStatistics()
    {
      std::string output_statistics = "Receiver Log Statistics: " + std::to_string(total_log_count_) + "; unknown: "   + std::to_string(unknown_msg_num_)
                                                       + "; discarded: " + std::to_string(discarded_msg_num_);

      for(log_count_map_t::iterator itr = log_counts_.begin();
                                    itr != log_counts_.end();
                                    itr++)
      {
        int  id    = itr->first;
        long count = itr->second;
        output_statistics += "; Log[" + std::to_string(id) + "]:" + std::to_string(count);
      }
      
      RCLCPP_INFO_STREAM(get_logger(), output_statistics);
    }
```

Does this resolve your issue of having a polluted output log?

**Comment by reinzor** [comment]
Thanks for coming back @novatel-applications-engineering ; this would already help but is unfortunately not sufficient for us. I agree with @Timple that incorporating this into diagnostics would be the proper solution. This would enable the user to look up these statistics when desired. It is always a matter of taste but in my opinion periodic logs from drivers (in nominal mode) should never end up in a level higher than DEBUG.

**Comment by novatel-applications-engineering** [comment]
Thanks @reinzor for the feedback. 

We will go ahead and apply your initially requested change. I am also updating another periodic log that gets reported of the IMU scale factors to change that from INFO to DEBUG. That should clear all of the regularly published logs in nominal mode.

I am raising this request internally to also update our features request list to have a diagnostics topic also include the log statistics.

**Pull request merged**
